### ISSUE TITLE
'Draw a box' - Popup modal

### ISSUE THREAD

**Issue by daZebra** [open-data-rescue/climate-data-rescue#15]
**Issue**
The first time(s) that I used the transcription bar, I did not notice that I had to Draw a box before moving on to the next transcription - I did not notice the message at the top of the screen.

**Potential solution**
Have a popup modal show every time the data is submitted. Also, disable the 'new transcription' button until the box is drawn.
Something like this:

![screen shot 2016-08-31 at 12 59 24 pm](https://cloud.githubusercontent.com/assets/14224342/18139705/8acc0404-6f80-11e6-8024-7852e5e358be.png)

**Comment by rsmithlal** [comment]
This is a great idea. Any suggestions to improve the transcription workflow are greatly appreciated!
