### ISSUE TITLE
Transcription bar - Flow

### ISSUE THREAD

**Issue by daZebra** [open-data-rescue/climate-data-rescue#18]
**Issue**
As a user, I find it slightly annoying to have to re-enter the date and time for every 'field group' as well as being interrupted every time I finish one to draw a box around the transcribed observations.
For a standard Type_A1 page, the user has to enter the 'observation time' & draw a box & re-click on the 'new annotation' button a total of 9 times to finish a single line.

**Potential solution 1**
When the user clicks submit for one of the 'field groups' she is taken to the field group directly to the right. The data is thus only submitted once the entire line has been transcribed. Then the user is asked to draw a box over the entire line.

_Pros_
- Fewer steps.

_Cons_
- The user would have to enter the entire line of data before it is saved.
- Complicated to implement from what I understood from Rob.

**Potential solution 2**
When the user finishes drawing the box, she is automatically taken back to the transcription bar (saves them from having to re-open it and drag it back into place).

**Comment by daZebra** [comment]
You can get a better idea of what I had in mind by navigating the transcription on the Mockup:
https://app.moqups.com/jeremycullen7@gmail.com/eykaYOP8/view/page/a0d70912f (let me know if the link doesn't work for you)

**Comment by rsmithlal** [comment]
I really like your gif for drawing the the annotation box in the modal

**Comment by rsmithlal** [comment]
The moqups are hosted from your personal account, will we potentially have any access issues once you finish with the project?

**Comment by daZebra** [comment]
As long as I keep paying, there should be no problem. If I do decide to cancel my subscription, I will export it as a PDF. But from that point on it will no longer be possible to edit the Mockup (except in Illustrator). Moreover, while the links are conserved in the PDF version, gifs show up as static images, and larger images are distorted - so it's not perfect.

**Comment by balen** [comment]
Old issue - not sure what was decided and noone knows
