### ISSUE TITLE
Amend Upload Script to hide pages

### ISSUE THREAD

**Issue by raakal** [open-data-rescue/climate-data-rescue#193]
Currently when uploading a page to the app it doesn't hide the pages automatically, and users are expected to add the metadata about the page in before transcribing.

Change requested is that the script be amended to default to hiding the pages, allowing for a team member to input the metadata behind the scenes and then switch the page to visible for users to begin transcribing. The goal is to make the transcribing experience easier for users.

Copy of the script and changed script should be created and saved for documentation purposes.

**Comment by raakal** [comment]
@rsmithlal @mcagan 

What is the status on this enhancement?

**Comment by mcagan** [comment]
Should be fixed with the latest commit. @rsmithlal did we merge that to production?
