### ISSUE TITLE
Repeat Register Schema Creation

### ISSUE THREAD

**Issue by raakal** [open-data-rescue/climate-data-rescue#194]
On the Admin>Page Schema section of the website, we are noticing a bug where the uploading of pages is creating new iterations of the register type schema.

For example, there is already a register schema for Register 110, page 2 but at the bottom of the list there are 3 more Register Schemas created, one of which holds 425 pages. This issue occurs both on the test site and the live site. It is not affected by downloading the image from the Google Drive repository as it was tested with images from our main USB drive. A review of image file names determined that it is unlikely that this is what has caused the problem as well.

In addition, it has been occurring prior to late January 2020 as one of the images that was used to recreate a register schema was uploaded prior to that (as evidenced by the Master Image Spreadsheet).

Suggested workaround: manually move the pages from those extra register schemas to the proper register schema.

**Comment by raakal** [comment]
@rsmithlal What is the status on resolving this bug?

**Comment by VickyS08** [comment]
Register types are created when a page is uploaded. Extra register types are occasionally spuriously created

**Comment by VickyS08** [comment]
Test uploaded pages on the DRAW-test site 2023-02-28; no duplicate schemas created
