### ISSUE TITLE
API Integration

### ISSUE THREAD

**Issue by raakal** [open-data-rescue/climate-data-rescue#195]
It's been suggested to integrate the SciStarter API into the web app. It would allow for DRAW to become eligible for special programming, etc.

All of the relevant documentation for the SciStarter API can be found here: https://scistarter.org/api

**Comment by rsmithlal** [comment]
How specifically would you want the API to be integrated? Precisely, what would you like to do with the API once we connect to it?

**Comment by VickyS08** [comment]
What does it do?
Mostly we want people to find us. If there are features which will make that easier, or make it easier for teachers say to use our site, then that would be good. Without knowing how their API works it’s hard to say.

Vicky
