### ISSUE TITLE
Certificate for Volunteer Hours

### ISSUE THREAD

**Issue by raakal** [open-data-rescue/climate-data-rescue#196]
We hope to add an element into the new Educator's Corner (citsci.geog.mcgill.ca/en/educate) which will enable a user to generate a certificate which would show them how many hours of transcribing they have completed. This feature would allow us to complete further educational outreach, as this certificate could be used for volunteer hour requirements in schools (or on the Co-Curricular Record at McGill University).

Ideal: 
A button on the Educator's Corner which when clicked would generate a certificate declaring how many hours of transcription were completed by the user. 
The certificate would be populated with data called from the database by a script/code and would include the user information, date of transcription (maybe a time frame), and the number of transcriptions they have completed turned into hours. This would be a predetermined unit of conversion based on average transcription rates (refer to past conversations in DRAW minute meetings).

**Comment by rsmithlal** [comment]
This is a great idea!
