### ISSUE TITLE
Draw a Box - Rolling Pop-ups

### ISSUE THREAD

**Issue by raakal** [open-data-rescue/climate-data-rescue#230]
@rsmithlal @y2749zha 

After transcribing an entire section successfully and you have drawn the annotation box, selecting the 'Mark annotated area and don't show me again' option on the tutorial pop-up has a bug that causes rolling pop-ups to appear. The tutorial pop-up does not disappear, and it will cause the blue coloured annotation popups to appear in multiples, blocking the screen and slowing down the transcription process. If you have completed 6 sections and drawn six annotation boxes, you will have 6 popups for example (see image).

A work around for the moment is refreshing the page between transcribing tabs, or by closing and re-opening the transcriber panel after each row of data, but it has been observed that this does not always help resolve the issue.

Suggested fix: disabling the pop-up feature for the time being to see if this helps.

<img width="240" alt="anno box" src="https://user-images.githubusercontent.com/46582468/83194994-84053c00-a107-11ea-9e82-4677b1c4238d.png">

**Comment by raakal** [comment]
@rsmithlal Can we disable the box drawing for the moment?

**Comment by rsmithlal** [comment]
You mean disable the message?

**Comment by raakal** [comment]
Yes, I believe so. Vicky mentioned it in the meeting tonight.

**Comment by VickyS08** [comment]
Several users have told me they stopped transcribing because they were confused by the multiple pop-up messages - along the lines of “but I just drew the box, why do I need to draw another one?”, or were seriously slowed down by having to reload the page or wait for the multiple boxes to disappear once they understood it was a bug. And these are just the ones I know about through personal contact.

Part of this goes back to people not reading the help text/ bug reports/ etc, but it’s causing us to lose users due to confusion or slowing down the process.

**Comment by rsmithlal** [comment]
Ok, that's good to know. I will try to get this done ASAP and deploy a new version to the server

**Comment by VickyS08** [comment]
That would be great, thanks!

Vicky

**Comment by rsmithlal** [comment]
Where the message is triggered https://github.com/open-data-rescue/climate-data-rescue/blob/aa00a34c7ebbf2a401ccef6d4bbfb821a7b5b16f/app/views/shared/_transcriber_app.html.erb#L111

**Comment by rsmithlal** [comment]
The plugin http://bootstrap-notify.remabledesigns.com/

**Comment by rsmithlal** [comment]
The problematic callback https://github.com/open-data-rescue/climate-data-rescue/blob/aa00a34c7ebbf2a401ccef6d4bbfb821a7b5b16f/app/views/shared/_transcriber_app.html.erb#L780

**Comment by rsmithlal** [comment]
Blue message trigger https://github.com/open-data-rescue/climate-data-rescue/blob/aa00a34c7ebbf2a401ccef6d4bbfb821a7b5b16f/app/views/shared/_transcriber_app.html.erb#L1097
