### ISSUE TITLE
Fields in Wrong Order

### ISSUE THREAD

**Issue by raakal** [open-data-rescue/climate-data-rescue#231]
A serious bug has cropped up where the variables in the transcriber's panel do not match the order in the logbook (they are switched around). This means that users may not have realized and have transcribed the wrong data into these fields.

@rsmithlal  notes that everything seems to be ok in the database and the code, and the logic for this hasn't been modified in quite some time.

On another instance of this app, the variables were in the wrong order as well and it was "fixed" by creating new field types and associating them with the page schemas, but this means data already transcribed in the existing field types will no longer be associated with those pages. While we don't loose the data, we do loose the traceability and it will need to be a step added in post-processing. 

Here is a list of instances of this bug so far:
https://docs.google.com/document/d/1XG5jwBra9Vna1QzD0JBzhMQs_t97vWlcY1lgLbngrvQ/edit?usp=sharing

![screenshot_issue1878-06-03 to 1878-06-05](https://user-images.githubusercontent.com/46582468/83196011-27a31c00-a109-11ea-815c-bdbb8a6794b6.png)

For the moment all pages found with this issue are hidden from users and unable to be transcribed.

**Comment by raakal** [comment]
@rsmithlal What's the status on this bug?

**Comment by rsmithlal** [comment]
This should be resolved now with the latest patch. The way that I preloaded the data related to field groups affected the order of the fields. Please reopen it if you ever encounter it again.
