### ISSUE TITLE
[DRAW-007] Grammatical issues appear in the transcription pop-up tabs

### ISSUE THREAD

**Issue by Tiffanyhi** [open-data-rescue/climate-data-rescue#57]
Steps to reproduce:
1. Navigate to a new transcription.
2. Select ‘transcribe’ button to prompt transcription pop-up.
3. Observe each of the tabs (ex: 'Barometer', 'Clouds', etc.).

Recommended result:
Capitalization and punctuation should appear in the transcription pop-up tabs.

Actual result:
Grammatical issues appear in the transcription pop-up tabs. 
For 'Temperature and humidity of the Air', the H in humidity should be capitalized. Also, there is a lack of capitalization on the descriptions presently available (under ‘Temperature and humidity of the Air’ and ‘Rain and Snow’ tabs). As such, these descriptions appear completely in lower case, with no punctuation.

Notes:
Tested on:
Google Chrome Version 55.0.2883.87 m, Internet Explorer 11, Firefox version 37.0.1.
Windows 7 Professional x32, Intel Cote i5, ATI Radeon HD 4550.
Repro rate: 5/5.

Screenshots attached: DRAW-007.png

Tiffany Hirsch

![draw-007](https://cloud.githubusercontent.com/assets/25228995/22126441/a16f4e10-de65-11e6-96df-5b3a440f11c6.png)

**Comment by rsmithlal** [comment]
This is a content issue, not a bug. These texts are uploaded and editable from the app admin interface
