### ISSUE TITLE
[DRAW-017] Cannot enter or edit data within transcription box when using Internet Explorer

### ISSUE THREAD

**Issue by Tiffanyhi** [open-data-rescue/climate-data-rescue#67]
Steps to reproduce:
1. Launch DRAW website using Internet Explorer.
2. Start a new transcription. 
3.  Select any of the tabs (ex: Barometer, Clouds, etc.) and attempt to add data in any of the fields.
4. Observe fields remaining blank, even if trying to type within them.

Actual result:
When using Internet Explorer, the user cannot enter or edit data within transcription box. When attempting to enter data, the fields remain blank. In addition, none of the drop-down options are visible for any of the fields. 

Expected result:
Drop-down options should be visible. Also, the user should be able to enter data in the fields.

Notes:
Issue occurs on:
Internet Explorer 11. 
Issue does not occur on: Google Chrome Version 55.0.2883.87 m, Firefox version 37.0.1.
Windows 7 Professional x32, Intel Cote i5, ATI Radeon HD 4550.
Repro rate: 5/5.

Screenshots attached: DRAW-017.png

Tiffany Hirsch

![draw-017](https://cloud.githubusercontent.com/assets/25228995/22352152/eddc6e80-e3e8-11e6-9d7b-b4319b85cb0b.png)

**Comment by rsmithlal** [comment]
Closing this issue because we are not supporting internet explorer
