### ISSUE TITLE
[DRAW-023]  Buttons on ‘My Transcriptions’ are misaligned when browser is resized to 891 x 740 or less

### ISSUE THREAD

**Issue by Tiffanyhi** [open-data-rescue/climate-data-rescue#73]
Steps to reproduce:
1. Launch DRAW website.
2. Navigate to ‘My Transcriptions’ by selecting the ‘Transcribe’ tab, then ‘My Transcriptions’ on the drop-down.
3. Resize browser to 891 x 740 or less.
4. Observe buttons misaligning when browser is resized. 

Actual result:
Buttons on ‘My Transcriptions’ are misaligned when browser is resized to 891 x 740 or less.

Expected result:
Buttons should properly align with page when browser is resized. 

Notes:
Issue occurs on:
Google Chrome Version 55.0.2883.87 m, Firefox version 37.0.1., Internet Explorer 11.
Tested on: Windows 7 Professional x32, Intel Cote i5, ATI Radeon HD 4550.
Repro rate: 5/5.

Screenshots attached: DRAW-023.png

![draw-023](https://cloud.githubusercontent.com/assets/25228995/24763811/7d0fb734-1ac0-11e7-90cd-a940976af191.png)

**Comment by rsmithlal** [comment]
This has been resolved. Please test and confirm, then close.

**Comment by balen** [comment]
No longer an issue with the new table
